import { describe, expect, it } from 'vitest';
import { main } from '../src/templates/main';
import { en } from '../src/locales/en';
import { settingsSchema } from '../src/utils/schemas';

describe('P0 regression coverage', () => {
    it('treats an empty settings control as omitted for single-field updates', () => {
        expect(settingsSchema.safeParse({ username: 'new_admin', password: '' }).success).toBe(true);
        expect(settingsSchema.safeParse({ username: '', password: 'CorrectHorseBatteryStaple2!' }).success).toBe(true);
    });

    it('HTML-encodes locale strings before placing them in Alpine expressions', () => {
        const rendered = main({ ...en, lang: 'en' });
        expect(rendered).toContain('&quot;It&#39;s empty here&quot;');
    });
});

// Domain suites: each file self-contained with its own env harness.
import './suites/folders.suite';
import './suites/auth.suite';
import './suites/init.suite';
import './suites/frontend.suite';
import './suites/import.suite';
import './suites/trash.suite';
import './suites/data.suite';
import './suites/folderdepth.suite';
import './suites/ratelimit.suite';
import './suites/reorder.suite';
import './suites/bookmarkreorder.suite';
import './suites/reorderbounded.suite';
import './suites/reorder2.suite';
import './suites/reorder3.suite';
import './suites/password.suite';
import './suites/password2.suite';
import './suites/password3.suite';
import './suites/passwordv4.suite';
import './suites/passwordmigration.suite';
import './suites/settings.suite';
import './suites/settings2.suite';
import './suites/logout.suite';
import './suites/race.suite';
import './suites/race2.suite';
import './suites/search.suite';
import './suites/validation.suite';
import './suites/ratelimitlogin.suite';
import './suites/importsize.suite';
import './suites/importdry.suite';
import './suites/importcsp.suite';
import './suites/importlimits.suite';
import './suites/importlarge.suite';
import './suites/importmalformed.suite';
import './suites/importcancel.suite';
import './suites/importlang.suite';
import './suites/importcascade.suite';
import './suites/importcount.suite';
import './suites/importdepth.suite';
import './suites/importsnapshot.suite';
import './suites/importdedupfail.suite';
import './suites/importtrash.suite';
import './suites/importmigration.suite';
import './suites/importentities.suite';
import './suites/importtriggers.suite';
import './suites/importinit.suite';
import './suites/initsecret.suite';
import './suites/initfails.suite';
import './suites/clienttrash.suite';
import './suites/clientsession.suite';
import './suites/clientstale.suite';
import './suites/clientauth.suite';
import './suites/clientlogout.suite';
import './suites/clientcreds.suite';
import './suites/clientcounts.suite';
import './suites/clientroundtrip.suite';
import './suites/exportsort.suite';
import './suites/exportorphan.suite';
import './suites/clientinit.suite';
import './suites/idempotency.suite';
import './suites/ideminvalid.suite';
import './suites/config.suite';
import './suites/ratelimitfail.suite';
import './suites/ratelimithrow.suite';
import './suites/ratelimitttl.suite';
import './suites/ratelimitclamp.suite';
import './suites/reorderbudget.suite';
import './suites/folderreorderbudget.suite';
import './suites/importbudget.suite';
import './suites/passwordbudget.suite';
import './suites/folderroundtrip.suite';
import './suites/clientguards.suite';
